//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhuCachLy.Model
{
    using QuanLyKhuCachLy.ViewModel;
    using System;
    using System.Collections.Generic;

    public partial class Address : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.DestinationHistories = new HashSet<DestinationHistory>();
            this.QuarantineAreas = new HashSet<QuarantineArea>();
            this.QuarantinePersons = new HashSet<QuarantinePerson>();
            this.Staffs = new HashSet<Staff>();
        }

        public int id { get; set; }

        private string _province;
        public string province
        {
            get => _province; set
            {
                _province = value;
                OnPropertyChanged();
            }
        }

        private string _district;
        public string district
        {
            get => _district; set
            {
                _district = value;
                OnPropertyChanged();
            }
        }

        private string _ward;
        public string ward
        {
            get => _ward; set
            {
                _ward = value;
                OnPropertyChanged();
            }
        }

        private string _streetName;
        public string streetName
        {
            get => _streetName; set
            {
                _streetName = value;
                OnPropertyChanged();
            }
        }

        private string _apartmentNumber;
        public string apartmentNumber
        {
            get => _apartmentNumber; set
            {
                _apartmentNumber = value;
                OnPropertyChanged();
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DestinationHistory> DestinationHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuarantineArea> QuarantineAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuarantinePerson> QuarantinePersons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff> Staffs { get; set; }

        public bool CheckValidateProperty()
        {
            if (string.IsNullOrWhiteSpace(province) || string.IsNullOrWhiteSpace(district) || string.IsNullOrWhiteSpace(ward))
                return false;

            return true;
        }
    }
}