//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhuCachLy.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLKCLEntities : DbContext
    {
        public QLKCLEntities()
            : base("name=QLKCLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<DestinationHistory> DestinationHistories { get; set; }
        public virtual DbSet<DISTRICT> DISTRICTs { get; set; }
        public virtual DbSet<HealthInformation> HealthInformations { get; set; }
        public virtual DbSet<InjectionRecord> InjectionRecords { get; set; }
        public virtual DbSet<NATION> NATIONs { get; set; }
        public virtual DbSet<NotificationTemplate> NotificationTemplates { get; set; }
        public virtual DbSet<PROVINCE> PROVINCEs { get; set; }
        public virtual DbSet<QuarantineArea> QuarantineAreas { get; set; }
        public virtual DbSet<QuarantinePerson> QuarantinePersons { get; set; }
        public virtual DbSet<QuarantineRoom> QuarantineRooms { get; set; }
        public virtual DbSet<Severity> Severities { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<TestingResult> TestingResults { get; set; }
        public virtual DbSet<WARD> WARDs { get; set; }
    }
}
