//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhuCachLy.Model
{
    using QuanLyKhuCachLy.ViewModel;
    using System;
    using System.Collections.Generic;

    public partial class DestinationHistory : BaseViewModel
    {
        public int id { get; set; }

        private System.DateTime _dateArrive;
        public System.DateTime dateArrive
        {
            get => _dateArrive; set
            {
                _dateArrive = value;
                OnPropertyChanged();
            }
        }

        private Nullable<int> _quarantinePersonID;
        public Nullable<int> quarantinePersonID
        {
            get => _quarantinePersonID; set
            {
                _quarantinePersonID = value;
                OnPropertyChanged();
            }
        }

        private Nullable<int> _addressID;
        public Nullable<int> addressID
        {
            get => _addressID; set
            {
                _addressID = value;
                OnPropertyChanged();
            }
        }

        public virtual Address Address { get; set; }
        public virtual QuarantinePerson QuarantinePerson { get; set; }
    }
}
