//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhuCachLy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HealthInformation()
        {
            this.QuarantinePersons = new HashSet<QuarantinePerson>();
        }
    
        public int id { get; set; }
        public bool isFever { get; set; }
        public bool isCough { get; set; }
        public bool isSoreThroat { get; set; }
        public bool isLossOfTatse { get; set; }
        public bool isTired { get; set; }
        public bool isShortnessOfBreath { get; set; }
        public bool isOtherSymptoms { get; set; }
        public bool isDisease { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuarantinePerson> QuarantinePersons { get; set; }
    }
}
