//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhuCachLy.Model
{
    using QuanLyKhuCachLy.ViewModel;
    using System;
    using System.Collections.Generic;

    public partial class QuarantineRoom : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuarantineRoom()
        {
            this.QuarantinePersons = new HashSet<QuarantinePerson>();
        }

        public int id { get; set; }

        private string _displayName;
        public string displayName
        {
            get => _displayName; set
            {
                _displayName = value;
                OnPropertyChanged();
            }
        }

        private int _capacity;
        public int capacity
        {
            get => _capacity; set
            {
                _capacity = value;
                OnPropertyChanged();
            }
        }


        private string _available;
        public string available
        {
            get => _available; set
            {
                _available = value;
                OnPropertyChanged();
            }
        }

        private Nullable<int> _levelID;
        public Nullable<int> levelID
        {
            get => _levelID; set
            {
                _levelID = value;
                OnPropertyChanged();
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuarantinePerson> QuarantinePersons { get; set; }

        private Severity _Severity;
        public virtual Severity Severity { get => _Severity; set { _Severity = value; OnPropertyChanged(); } }

        public bool CheckValidateProperty()
        {
            if (string.IsNullOrWhiteSpace(displayName) || capacity <= 0)
                return false;

            return true;
        }
    }
}