//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhuCachLy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuarantinePerson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuarantinePerson()
        {
            this.DestinationHistories = new HashSet<DestinationHistory>();
            this.InjectionRecords = new HashSet<InjectionRecord>();
            this.TestingResults = new HashSet<TestingResult>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public string sex { get; set; }
        public string citizenID { get; set; }
        public string nationality { get; set; }
        public string healthInsuranceID { get; set; }
        public string phoneNumber { get; set; }
        public int levelID { get; set; }
        public System.DateTime arrivedDate { get; set; }
        public System.DateTime leaveDate { get; set; }
        public int quarantineDays { get; set; }
        public Nullable<int> addressID { get; set; }
        public Nullable<int> healthInformationID { get; set; }
        public Nullable<int> roomID { get; set; }
    
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DestinationHistory> DestinationHistories { get; set; }
        public virtual HealthInformation HealthInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InjectionRecord> InjectionRecords { get; set; }
        public virtual Severity Severity { get; set; }
        public virtual QuarantineRoom QuarantineRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestingResult> TestingResults { get; set; }
    }
}
