//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhuCachLy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.QuarantineAreas = new HashSet<QuarantineArea>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public string sex { get; set; }
        public string citizenID { get; set; }
        public string nationality { get; set; }
        public string healthInsuranceID { get; set; }
        public string phoneNumber { get; set; }
        public int addressID { get; set; }
        public string jobTitle { get; set; }
        public string department { get; set; }
    
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuarantineArea> QuarantineAreas { get; set; }
    }
}
