//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhuCachLy.Model
{
    using QuanLyKhuCachLy.ViewModel;
    using System;
    using System.Collections.Generic;

    public partial class TestingResult : BaseViewModel
    {
        public int id { get; set; }

        private System.DateTime _dateTesting;
        public System.DateTime dateTesting
        {
            get => _dateTesting; set
            {
                _dateTesting = value;
                OnPropertyChanged();
            }
        }

        private bool _isPositive;
        public bool isPositive
        {
            get => _isPositive; set
            {
                _isPositive = value;
                OnPropertyChanged();
            }
        }

        private int _quarantinePersonID;
        public int quarantinePersonID
        {
            get => _quarantinePersonID; set
            {
                _quarantinePersonID = value;
                OnPropertyChanged();
            }
        }

        public virtual QuarantinePerson QuarantinePerson { get; set; }
    }
}